MEMORY
{
  # We pass `-m 128` to qemu but it allocates stuff in the top 16 MiB
  RAM : ORIGIN = 0x80000000, LENGTH = 112M
}

REGION_ALIAS("REGION_TEXT", RAM);
REGION_ALIAS("REGION_RODATA", RAM);

REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
